In [14]:
import requests
import pandas

In [15]:
abbr = "NY"

In [16]:
st_summary = requests.get('https://colorado.rstudio.com/rsc/access-to-care/api/summary?state=' + abbr)

In [17]:
st_summary.text

'[{"state":"NY","hospitals":147,"population":19795791,"under":4,"counties":62,"state_id":33,"full":"New York"}]'

In [18]:
pandas.DataFrame.from_dict(st_summary.json())

  state  hospitals  population  under  counties  state_id      full
0    NY        147    19795791      4        62        33  New York

In [19]:
st_detail = requests.get('https://colorado.rstudio.com/rsc/access-to-care/api/state?state=' + abbr)

In [20]:
counties = pandas.DataFrame.from_dict(st_detail.json())

In [21]:
counties.nlargest(10, 'population')

,state_id,full,state,county_id,county,population,hospitals,fit,lwr,upr,result,population_label,popup,color
23,33,New York,NY,1974,Kings,2636735,12,18,15,20,Under,3M,<b>Kings</b><br/>Population: 3M<br/>Hospitals:...,#CC79A7
40,33,New York,NY,1991,Queens,2339150,6,16,14,18,Under,2M,<b>Queens</b><br/>Population: 2M<br/>Hospitals...,#CC79A7
30,33,New York,NY,1981,New York,1644518,12,11,9,14,Acceptable,2M,<b>New York</b><br/>Population: 2M<br/>Hospita...,#008b00
51,33,New York,NY,2002,Suffolk,1501587,10,10,8,13,Acceptable,2M,<b>Suffolk</b><br/>Population: 2M<br/>Hospital...,#008b00
2,33,New York,NY,1953,Bronx,1455444,6,10,8,12,Under,1M,<b>Bronx</b><br/>Population: 1M<br/>Hospitals:...,#CC79A7
29,33,New York,NY,1980,Nassau,1361350,10,10,7,12,Acceptable,1M,<b>Nassau</b><br/>Population: 1M<br/>Hospitals...,#008b00
59,33,New York,NY,2010,Westchester,976396,0,7,5,9,Under,976K,<b>Westchester</b><br/>Population: 976K<br/>Ho...,#CC79A7
14,33,New York,NY,1965,Erie,922578,7,7,4,9,Acceptable,923K,<b>Erie</b><br/>Population: 923K<br/>Hospitals...,#008b00
27,33,New York,NY,1978,Monroe,749600,5,6,3,8,Acceptable,750K,<b>Monroe</b><br/>Population: 750K<br/>Hospita...,#008b00
42,33,New York,NY,1993,Richmond,474558,2,4,2,6,Acceptable,475K,<b>Richmond</b><br/>Population: 475K<br/>Hospi...,#008b00

counties.nlargest(10, 'hospitals')

In [22]:
counties[counties.result == "Under"]

,state_id,full,state,county_id,county,population,hospitals,fit,lwr,upr,result,population_label,popup,color
2,33,New York,NY,1953,Bronx,1455444,6,10,8,12,Under,1M,<b>Bronx</b><br/>Population: 1M<br/>Hospitals:...,#CC79A7
23,33,New York,NY,1974,Kings,2636735,12,18,15,20,Under,3M,<b>Kings</b><br/>Population: 3M<br/>Hospitals:...,#CC79A7
40,33,New York,NY,1991,Queens,2339150,6,16,14,18,Under,2M,<b>Queens</b><br/>Population: 2M<br/>Hospitals...,#CC79A7
59,33,New York,NY,2010,Westchester,976396,0,7,5,9,Under,976K,<b>Westchester</b><br/>Population: 976K<br/>Ho...,#CC79A7